services:
  keycloak-db:
    image: postgres:15
    container_name: keycloak-db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${KEYCLOAK_DB_NAME}
      POSTGRES_USER: ${KEYCLOAK_DB_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    ports:
      - "${KEYCLOAK_DB_PORT}:5432"
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    networks:
      - retail-platform
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h keycloak-db -U ${KEYCLOAK_DB_USER} -d ${KEYCLOAK_DB_NAME}"]
      interval: 10s
      retries: 10
      timeout: 5s

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    container_name: keycloak
    env_file:
      - .env
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_USERNAME: ${KEYCLOAK_DB_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KC_DB_DATABASE: ${KEYCLOAK_DB_NAME}
      KC_HEALTH_ENABLED: "true"
    command: start-dev
    ports:
      - "${KEYCLOAK_PORT}:8080"
    networks:
      - retail-platform
    depends_on:
      keycloak-db:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://keycloak:8080/realms/master || exit 1"]
      interval: 10s
      retries: 10
      timeout: 10s

  auth-db:
    image: postgres:15
    container_name: auth-db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${AUTH_DB_NAME}
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
    ports:
      - "${AUTH_DB_PORT}:5432"
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    networks:
      - retail-platform
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h auth-db -U ${AUTH_DB_USER} -d ${AUTH_DB_NAME}"]
      interval: 10s
      retries: 10
      timeout: 5s

  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    container_name: auth-service
    env_file:
      - .env
    ports:
      - "${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}"
    depends_on:
      keycloak:
        condition: service_healthy
      auth-db:
        condition: service_healthy
    environment:
      KEYCLOAK_URL: http://keycloak:${KEYCLOAK_PORT}
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-db:5432/${AUTH_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${AUTH_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${AUTH_DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
      SPRING_JPA_SHOW_SQL: ${SPRING_JPA_SHOW_SQL}
      LOG_PATH: /app/logs
      SERVER_PORT: ${AUTH_SERVICE_PORT}
    restart: unless-stopped
    volumes:
      - maven-repo:/root/.m2
      - ./auth-logs:/app/logs
    networks:
      - retail-platform

volumes:
  keycloak-db-data:
  auth-db-data:
  maven-repo:

networks:
  retail-platform:
    driver: bridge
