version: '3.9'

services:
  redis:
    image: redis:7
    container_name: ${REDIS_SERVICE_NAME}
    env_file:
      - .env
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - retail-platform
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli ping"]
      interval: ${REDIS_HEALTHCHECK_INTERVAL}
      timeout: ${REDIS_HEALTHCHECK_TIMEOUT}
      retries: ${REDIS_HEALTHCHECK_RETRIES}

  jwt-service:
    build:
      context: .
      dockerfile: ${JWT_SERVICE_DOCKERFILE}
    container_name: ${JWT_SERVICE_NAME}
    env_file:
      - .env
    ports:
      - "${JWT_SERVICE_PORT}:${JWT_SERVICE_PORT}"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      REDIS_HOST: ${REDIS_SERVICE_NAME}
      REDIS_PORT: ${REDIS_PORT}
      LOG_PATH: ${JWT_SERVICE_LOG_PATH}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
      SPRING_JPA_SHOW_SQL: ${SPRING_JPA_SHOW_SQL}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SERVER_PORT: ${JWT_SERVICE_PORT}
      USER_SERVICE_URL: ${USER_SERVICE_URL}
      LOG_LEVEL_ROOT: ${JWT_SERVICE_LOG_LEVEL_ROOT}
      LOG_LEVEL_SPRING: ${JWT_SERVICE_LOG_LEVEL_SPRING}
      LOG_LEVEL_SPRING_SECURITY: ${JWT_SERVICE_LOG_LEVEL_SPRING_SECURITY}
      LOG_LEVEL_SPRING_SECURITY_WEB: ${JWT_SERVICE_LOG_LEVEL_SPRING_SECURITY_WEB}
      LOG_LEVEL_FILTER_CHAIN: ${JWT_SERVICE_LOG_LEVEL_FILTER_CHAIN}
      LOG_LEVEL_AUTHENTICATION: ${JWT_SERVICE_LOG_LEVEL_AUTHENTICATION}
      LOG_LEVEL_APP: ${JWT_SERVICE_LOG_LEVEL_APP}
      LOG_PATTERN_CONSOLE: ${JWT_SERVICE_LOG_PATTERN_CONSOLE}
    restart: unless-stopped
    volumes:
      - maven-repo:/root/.m2
      - ${JWT_SERVICE_LOGS}:${JWT_SERVICE_LOG_PATH}
    networks:
      - retail-platform
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://${JWT_SERVICE_NAME}:${JWT_SERVICE_PORT}/actuator/health || exit 1"]
      interval: ${JWT_SERVICE_HEALTHCHECK_INTERVAL}
      retries: ${JWT_SERVICE_HEALTHCHECK_RETRIES}
      timeout: ${JWT_SERVICE_HEALTHCHECK_TIMEOUT}

volumes:
  maven-repo:

networks:
  retail-platform:
    driver: bridge
