services:
  # ------------------------
  # Keycloak
  # ------------------------
  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev --import-realm
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    networks:
      - retail-platform

  # ------------------------
  # Auth Service
  # ------------------------
  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
      - "9082:9082"
    depends_on:
      - keycloak
    networks:
      - retail-platform

  # ------------------------
  # User Service
  # ------------------------
  user-service:
    build:
      context: ./user-service
    container_name: user-service
    ports:
      - "9083:9083"
    depends_on:
      - auth-service
      - keycloak
    networks:
      - retail-platform

networks:
  retail-platform:
    driver: bridge
