# docker-compose.yml
services:
  # ----------------------
  # Keycloak
  # ----------------------
  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
    command: start-dev
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - retail-platform

  # ----------------------
  # Auth Service
  # ----------------------
  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    ports:
      - "9082:9082"
    depends_on:
      - keycloak
    environment:
      KEYCLOAK_URL: http://keycloak:8080
    restart: on-failure
    volumes:
      - maven-repo:/root/.m2
    networks:
      - retail-platform

  # ----------------------
  # User Service
  # ----------------------
  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    ports:
      - "9083:9083"
    depends_on:
      - keycloak
      - auth-service
    environment:
      AUTH_SERVICE_URL: http://auth-service:9082
      KEYCLOAK_URL: http://keycloak:8080
    restart: on-failure
    volumes:
      - maven-repo:/root/.m2
    networks:
      - retail-platform

# ----------------------
# Volumes
# ----------------------
volumes:
  maven-repo:

# ----------------------
# Networks
# ----------------------
networks:
  retail-platform:
    driver: bridge
