{
 "title": "User Service Metrics",
 "tags": [
  "metrics",
  "user-service"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 6 },
   "targets": [
    { "expr": "process_cpu_usage" }
   ]
  },
  {
   "title": "Heap Memory Usage",
   "type": "gauge",
   "gridPos": { "x": 6, "y": 0, "w": 6, "h": 6 },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\"}"
    }
   ]
  },
  {
   "title": "HTTP Requests per Endpoint",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 6, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count[1m])",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "DB Connection Pool Usage",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 6, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "hikaricp_connections_active{pool=\"HikariPool-1\"}",
     "legendFormat": "Active Connections"
    },
    {
     "expr": "hikaricp_connections_idle{pool=\"HikariPool-1\"}",
     "legendFormat": "Idle Connections"
    }
   ]
  }
 ]
}