receivers:
  otlp:
    protocols:
      grpc: {}   # OTLP gRPC from services (4317)
      http: {}   # OTLP HTTP from services (4318)

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"

  otlphttp/tempo:
    endpoint: "http://tempo:3200"   # Tempo ingestion endpoint
    tls:
      insecure: true
    headers:
      "Content-Type": "application/x-protobuf"

processors:
  batch: {}
  memory_limiter:
    check_interval: 1s
    limit_mib: 4000
    spike_limit_mib: 500

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, memory_limiter]
      exporters: [otlphttp/tempo]

    metrics:
      receivers: [otlp]
      processors: [batch, memory_limiter]
      exporters: [prometheus]
