apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    uid: prometheus-main

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    uid: tempo-main

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    uid: loki-main
